

echo1:
	echo "lệnh echo test 1"
echo2:
	@echo "lệnh echo test 2"
echo3:
	@echo lệnh echo test 2

Touch:
	@echo "đã tạo file test.txt"
	touch test.txt

Mkdir:
	@echo "đã tạo folder VD_mkdir"
	touch VD_mkdir

clean:
	@echo "đã xóa file test.txt và folder VD_mkdir"
	rm -f VD_mkdir
	rm -rf test.txt

